name: NezTemplate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: | 
          3.1.x
          6.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./Source/NezTemplate.sln
      
    - name: Build
      run: dotnet build ./Source/NezTemplate.sln --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Source/NezTemplate.sln
